# Configuración para Railway
# Este archivo le dice a Railway cómo buildear y ejecutar tu app

[build]
command = "npm install"

[deploy]
command = "npm start"

[env]
NODE_ENV = "production"
RAILWAY_ENVIRONMENT = "true"
